name: Deploy
run-name: Deploy started by ${{ github.actor }} 🚀
env:
  IMAGE_NAME: palette-creator
  IMAGE_TAG: ${{ github.sha }}
  # IMAGE_TAG: ${{ github.sha }}
  # IMAGE_REGISTRY_URL: registry.domain.com
on:
  workflow_dispatch:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]*"]
    # branches:
    #   - 'release/**'
jobs:
  build_image:
    runs-on: ubuntu-latest # could change to self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .
      # - name: Teardown
      #   run: docker rmi $IMAGE_REGISTRY_URL/$IMAGE_NAME:$IMAGE_TAG
